# Generated by Django 3.2 on 2021-09-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pokemon_id', models.PositiveIntegerField(unique=True)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('base_stats', models.JSONField()),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evolution_type', models.CharField(choices=[('Preevolution', 'Preevolution'), ('Evolution', 'Evolution')], default='Evolution', max_length=15)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='pokedex.pokemon')),
            ],
            options={
                'verbose_name': 'Evolution',
                'verbose_name_plural': 'Evolutions',
            },
        ),
    ]
